DI_RazorPages_Demo/Models/DeptEmpCount.cs
namespace DI_RazorPages_Demo.Models
{
    public class DeptEmpCount
    {
        public string Department { get; set; }
        public int Count { get; set; }

        public List<Employee> Employees { get; set; }

        StringBuilder sb = new StringBuilder();
    }
}

DI_RazorPages_Demo/Models/Employee.cs
namespace DI_RazorPages_Demo.Models
{
    public class Employee:IEmployee
    {

        static private List<Employee> employees = new List<Employee>();
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long Mobile { get; set; }
        public string Email { get; set; }

        public string Department { get; set; }

        public List<DeptEmpCount> GetDeptEmpCount()
        {
           return employees.GroupBy(t=>t.Department).Select(r=>new DeptEmpCount() { Department=r.Key,Count=r.Count()}).ToList();    
        }

        public List<Employee> GetEmployees()
        {
            employees.Add(new Employee() { EmployeeId = 1, FirstName = "Dhivya", LastName = "Rajendren", Mobile = 9976408018, Email = "dhivya@cloudKampus.com",Department="Training" });

            employees.Add(new Employee() { EmployeeId = 2, FirstName = "Sam", LastName = "Ashwin", Mobile = 7082583383, Email = "sam@cloudKampus.com" ,Department="IT Ops"});

            employees.Add(new Employee() { EmployeeId = 3, FirstName = "Aabha", LastName = "Kumar", Mobile = 9976708018, Email = "Aabha@cloudKampus.com", Department = "Training" });

            employees.Add(new Employee() { EmployeeId = 4, FirstName = "Sherin", LastName = "George", Mobile = 8082583383, Email = "sherin@cloudKampus.com", Department = "Sales" });

            return employees;

        }
    }
}

DI_RazorPages_Demo/Models/IEmployee.cs
namespace DI_RazorPages_Demo.Models
{
    public interface IEmployee
    {
        List<Employee> GetEmployees();
        List<DeptEmpCount> GetDeptEmpCount();
    }
}

DI_RazorPages_Demo/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace DI_RazorPages_Demo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DI_RazorPages_Demo/Pages/Index.cshtml.cs
using DI_RazorPages_Demo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DI_RazorPages_Demo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IConfiguration configuration;
        private readonly IEmployee employee;

        //constructor Injection
        public IndexModel(IConfiguration configuration,IEmployee employee)// Index model is controlling the object creation .//Inversion of Control -IoC
        {
            this.configuration = configuration;
            this.employee = employee;
        }

        public List<Employee> Employees { get; set; }

        public void OnGet()
        {
            configuration.GetConnectionString("");
            //   IEmployee employee = new Employee();// No direct dependency// Employee class controls the object creation 
            if (configuration.GetValue<bool>("Features:HomePage:EnableMessage"))
            {
                ViewData["Message"] = configuration.GetValue<string>("Features:HomePage:PageTitle");
            }

           Employees= employee.GetEmployees();
        }
    }
}

DI_RazorPages_Demo/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DI_RazorPages_Demo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

DI_RazorPages_Demo/ViewComponents/DeptCountViewComponent.cs
using DI_RazorPages_Demo.Models;
using Microsoft.AspNetCore.Mvc;

namespace DI_RazorPages_Demo.ViewComponents
{
    public class DeptCountViewComponent:ViewComponent
    {
        private readonly IEmployee employee;

        public DeptCountViewComponent(IEmployee employee)
        {
            this.employee = employee;
        }
        public IViewComponentResult Invoke()
        {

            return View(employee.GetDeptEmpCount());
        }
    }
}

DI_RazorPages_Demo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@await Component.InvokeAsync("DeptCount");
<div class="text-center">
    <h1 class="display-4">@ViewData["Message"]</h1>
   <table border="1">
       <tr>
           <th>Id</th>
           <td>FirstName</td>
           <td>Email</td>
       </tr>
       @foreach(var item in Model.Employees)
        {
            <tr>
                <td>@item.EmployeeId</td>
                <td>@item.FirstName</td>
                <td>@item.Email</td>
            </tr>
        }
    </table>
</div>

DI_RazorPages_Demo/Pages/Shared/Components/DeptCount/Default.cshtml
@model IEnumerable<DeptEmpCount>



<h3>Employee Count</h3>
<table border=1>
    <tr>
        <th>Department</th>
        <th>Count</th>
    </tr>
   @foreach(var item in Model)
    {
        <tr>
            <td>@item.Department</td>
            <td>@item.Count</td>
        </tr>
    }
</table>

DI_RazorPages_Demo/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DI_RazorPages_Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DI_RazorPages_Demo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">DI_RazorPages_Demo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DI_RazorPages_Demo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>